const INVALID_REQUEST = 'INVALID_REQUEST';
const UNAUTHORISED = 'UNAUTHORISED';
const SESSION_EXPIRED = 'SESSION_EXPIRED';
const TYPES  ={
    EMPLOYEE : 'employee',
    PROJECT_MANAGER : 'projectManager'
}
module.exports = {
    INVALID_REQUEST,
    UNAUTHORISED,
    SESSION_EXPIRED,
    TYPES
}